# Generated by rust2rpm 26
%bcond_with check

%global crate mdbook

Name:           rust-mdbook
Version:        0.4.37
Release:        %autorelease
Summary:        Creates a book from markdown files

License:        MPL-2.0
URL:            https://crates.io/crates/mdbook
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Creates a book from markdown files.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license src/theme/fonts/OPEN-SANS-LICENSE.txt
%license src/theme/fonts/SOURCE-CODE-PRO-LICENSE.txt
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/mdbook

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/src/theme/fonts/OPEN-SANS-LICENSE.txt
%license %{crate_instdir}/src/theme/fonts/SOURCE-CODE-PRO-LICENSE.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+search-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+search-devel %{_description}

This package contains library source intended for building other packages which
use the "search" feature of the "%{crate}" crate.

%files       -n %{name}+search-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serve-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serve-devel %{_description}

This package contains library source intended for building other packages which
use the "serve" feature of the "%{crate}" crate.

%files       -n %{name}+serve-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+watch-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+watch-devel %{_description}

This package contains library source intended for building other packages which
use the "watch" feature of the "%{crate}" crate.

%files       -n %{name}+watch-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n

%build
%cargo_build -n
%{cargo_license_summary -n}
%{cargo_license -n} > LICENSE.dependencies

%install
%cargo_install -n

%if %{with check}
%check
%cargo_test -n
%endif

%changelog
%autochangelog
