# Generated by rust2rpm 26
%bcond_with check

%global crate mdbook-linkcheck

Name:           rust-mdbook-linkcheck
Version:        0.7.7
Release:        %autorelease
Summary:        Backend for mdbook which will check your links for you

License:        MIT
URL:            https://crates.io/crates/mdbook-linkcheck
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          mdbook-linkcheck-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A backend for `mdbook` which will check your links for you.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/mdbook-linkcheck

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -n

%build
%cargo_build -n
%{cargo_license_summary -n}
%{cargo_license -n} > LICENSE.dependencies

%install
%cargo_install -n

%if %{with check}
%check
%cargo_test -n
%endif

%changelog
%autochangelog
